services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: https://github.com/tom-snow/alist-render.git # optional
    region: singapore # optional (defaults to singapore)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5244
      - key: DB_TYPE
        # value: sqlite3 (default) / mysql / postgres
        sync: false
      - key: DB_HOST
        # value: db_host (if set DB_TYPE = sqlite3, this and below DB setting is not needed)
        sync: false
      - key: DB_PORT
        # value: 3306
        sync: false
      - key: DB_USER
        # value: db_user
        sync: false
      - key: DB_PASS
        # value: db_password
        sync: false
      - key: DB_NAME
        # value: db_name
        sync: false
      - key: DB_TABLE_PREFIX
        # value: alist_
        sync: false
      - key: CDN
        # value: https://npm.elemecdn.com/alist-web@$version/dist
        sync: false